### ISSUE TITLE
Відредагувати в файлі README.md блок інформації про структуру проекту

### ISSUE THREAD

**Issue by YK911** [goitacademy/vanilla-app-template#1]
![vite-readme](https://user-images.githubusercontent.com/55898053/211682411-924755b3-e989-4583-9bf1-4873a48aa5fe.jpg)
Бажано відредагувати рядок з прикладом розміщення файлу стилей (відмічено на зображенні)

**Comment by luxplanjay** [comment]
@YK911 открой пр с правкой пожалуйста 🙏

**Comment by YK911** [comment]
Done ✅
