### ISSUE TITLE
js скрипт

### ISSUE THREAD

**Issue by spa-sam** [goitacademy/vanilla-app-template#13]
Коли робиш свій js скрипт куди його добавляти? Я зробив свій файл header_mobil_menu.js и поклав його біля  main.js добавив в index.html  
```
<load src="partials/footer.html" />
    <script type="module" src="/main.js"></script>
    <script src="/header_mobil_menu.js"></script>
  </body>
</html>
```
Він працює тілки локально на живій сторінці, а на github pg вже ні.

**Comment by YK911** [comment]
All script files must be imported into mian.js file
